services:
  portfolio:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
